package modelgen

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"
)

const SourceURL = "https://openrouter.ai/api/v1/models"

var ambiguousModelMentionKeys = map[string]struct{}{
	"auto":             {},
	"autorouter":       {},
	"bodybuilder":      {},
	"commanda":         {},
	"commandr":         {},
	"free":             {},
	"freemodelsrouter": {},
	"o1":               {},
	"o3":               {},
	"r1":               {},
	"router":           {},
	"saba":             {},
	"sonar":            {},
	"spotlight":        {},
	"uncensored":       {},
	"weaver":           {},
}

type OpenRouterResponse struct {
	Data []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"data"`
}

type Snapshot struct {
	SourceURL       string
	SourceItemCount int
	ModelCount      int
	ModelHash       string
	Models          []string
}

func BuildSnapshot(body []byte) (Snapshot, error) {
	if strings.TrimSpace(string(body)) == "" {
		return Snapshot{}, fmt.Errorf("empty response body")
	}

	var result OpenRouterResponse
	if err := json.Unmarshal(body, &result); err != nil {
		return Snapshot{}, fmt.Errorf("parse json: %w", err)
	}
	if len(result.Data) == 0 {
		return Snapshot{}, fmt.Errorf("response contained no models")
	}

	var models []string
	seen := make(map[string]struct{})
	for _, item := range result.Data {
		idParts := strings.Split(item.ID, "/")
		if len(idParts) == 2 {
			models, seen = addModel(models, seen, idParts[1])
		}

		name := item.Name
		nameParts := strings.SplitN(name, ": ", 2)
		if len(nameParts) == 2 {
			name = nameParts[1]
		}
		name = regexp.MustCompile(`\s*\(.*?\)`).ReplaceAllString(name, "")
		models, seen = addModel(models, seen, name)
	}

	sort.Strings(models)

	return Snapshot{
		SourceURL:       SourceURL,
		SourceItemCount: len(result.Data),
		ModelCount:      len(models),
		ModelHash:       hashModels(models),
		Models:          models,
	}, nil
}

func RenderModelsGo(w io.Writer, snapshot Snapshot) error {
	if snapshot.SourceURL == "" {
		snapshot.SourceURL = SourceURL
	}

	lines := []string{
		"// Code generated by generate.go; DO NOT EDIT.",
		fmt.Sprintf("// Source: %s", snapshot.SourceURL),
		fmt.Sprintf("// Source item count: %d", snapshot.SourceItemCount),
		fmt.Sprintf("// Normalized model count: %d", snapshot.ModelCount),
		fmt.Sprintf("// Normalized model SHA256: %s", snapshot.ModelHash),
		"package detection",
		"",
		"// GeneratedModelMentions contains the optional generated model catalogue.",
		"var GeneratedModelMentions = []string{",
	}

	for _, line := range lines {
		if _, err := fmt.Fprintln(w, line); err != nil {
			return err
		}
	}
	for _, model := range snapshot.Models {
		if _, err := fmt.Fprintf(w, "\t%q,\n", model); err != nil {
			return err
		}
	}
	_, err := fmt.Fprintln(w, "}")
	return err
}

func addModel(models []string, seen map[string]struct{}, model string) ([]string, map[string]struct{}) {
	model = strings.TrimSpace(model)
	key := strings.ToLower(model)
	if key == "" {
		return models, seen
	}
	if _, isAmbiguous := ambiguousModelMentionKeys[modelMentionKey(model)]; isAmbiguous {
		return models, seen
	}
	if _, ok := seen[key]; ok {
		return models, seen
	}

	models = append(models, model)
	seen[key] = struct{}{}
	return models, seen
}

func modelMentionKey(model string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' {
			return r
		}
		if r >= 'A' && r <= 'Z' {
			return r + ('a' - 'A')
		}
		if r >= '0' && r <= '9' {
			return r
		}
		return -1
	}, model)
}

func hashModels(models []string) string {
	sum := sha256.Sum256([]byte(strings.Join(models, "\n")))
	return hex.EncodeToString(sum[:])
}
