//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
)

var genericModelMentionIDs = map[string]struct{}{
	"command r":          {},
	"auto":               {},
	"auto router":        {},
	"free":               {},
	"free models router": {},
	"r1":                 {},
	"router":             {},
	"sonar":              {},
	"spotlight":          {},
}

type OpenRouterResponse struct {
	Data []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"data"`
}

func main() {
	resp, err := http.Get("https://openrouter.ai/api/v1/models")
	if err != nil {
		log.Fatalf("failed to fetch models: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		log.Fatalf("failed to fetch models: unexpected HTTP status %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("failed to read response: %v", err)
	}
	if strings.TrimSpace(string(body)) == "" {
		log.Fatal("failed to fetch models: empty response body")
	}

	var result OpenRouterResponse
	if err := json.Unmarshal(body, &result); err != nil {
		log.Fatalf("failed to parse json: %v", err)
	}
	if len(result.Data) == 0 {
		log.Fatal("failed to fetch models: response contained no models")
	}

	var models []string
	seen := make(map[string]struct{})

	for _, item := range result.Data {
		// ID usually looks like "anthropic/claude-3-opus"
		idParts := strings.Split(item.ID, "/")
		if len(idParts) == 2 {
			models, seen = addModel(models, seen, idParts[1])
		}

		name := item.Name
		nameParts := strings.SplitN(name, ": ", 2)
		if len(nameParts) == 2 {
			name = nameParts[1]
		}
		// remove "(free)", "(Fast)", etc.
		name = regexp.MustCompile(`\s*\(.*?\)`).ReplaceAllString(name, "")
		name = strings.TrimSpace(name)
		models, seen = addModel(models, seen, name)
	}

	sort.Strings(models)

	out, err := os.Create("../models.go")
	if err != nil {
		log.Fatalf("failed to create models.go: %v", err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by generate.go; DO NOT EDIT.")
	fmt.Fprintln(out, "package detection")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "func init() {")
	fmt.Fprintln(out, "\tSupportedToolsInMentions = appendCanonicalMentions(SupportedToolsInMentions, generatedModelMentions...)")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "var generatedModelMentions = []string{")
	for _, m := range models {
		fmt.Fprintf(out, "\t%q,\n", m)
	}
	fmt.Fprintln(out, "}")
}

func addModel(models []string, seen map[string]struct{}, model string) ([]string, map[string]struct{}) {
	model = strings.TrimSpace(model)
	key := strings.ToLower(model)
	if key == "" {
		return models, seen
	}
	if _, isGeneric := genericModelMentionIDs[key]; isGeneric {
		return models, seen
	}
	if _, ok := seen[key]; ok {
		return models, seen
	}

	models = append(models, model)
	seen[key] = struct{}{}
	return models, seen
}
